#!/bin/bash

# URL 목록
urls=(
    "k-eco.or.kr"
    "police-expo.com"
    "eng.police-expo.com"
    "suwonmesse.com"
    "messeesang.com"
    "eng.messeesang.com"
    "chemexpokorea.com/"
    "chemexpokorea.com/eng"
    "conference.messeesang.com"
    "members.messeesang.com"
    "hotelfair.co.kr"
    "modularkorea.com"
    "exhibitor.messeesang.com"
    "www.cleanairexpo.co.kr"
    "wp-test.messeesang.com/"
    "wp-test.messeesang.com/avada/"
    "wp-test.messeesang.com/divi/"
    "wp-test.messeesang.com/broker/"
    "wp-test.messeesang.com/job/"
    "smarthealthcareexpo.co.kr"
    "metavexpo.com"
    "metavexpo.com/eng"
    "komiexpo.org/"
    "komiexpo.org/eng"
    "k-artfair.co.kr"
    "k-artfair.co.kr/coex"
    "www.krefair.com"
    "www.buildingfiresafety.co.kr"
    "untactshow.com/"
    "illustrationkorea.co.kr/"
    "illustrationkorea.co.kr/exco/"
    "illustrationkorea.co.kr/spring/"
    "illustrationkorea.co.kr/coex/"
    "illustrationkorea.co.kr/kintex/"
    "illustrationkorea.co.kr/halloween/"
    "khospital.org/"
    "en.khospital.org/"
    "koreabuild.co.kr/"
    "koreabuild.co.kr/kintex/"
    "koreabuild.co.kr/coex/"
    "koreabuild.co.kr/eng/"
    "koreabuild.co.kr/bexco/"
    "koreabuild.co.kr/school/"
    "indeko.co.kr"
    "khfair.com/"
    "khfair.com/gwangju/"
    "khfair.com/coex/"
    "khfair.com/eng/"
    "khfair.com/setec/"
    "khfair.com/jeju/"
    "khfair.com/daegu/"
    "khfair.com/suwon/"
    "handarty.co.kr/"
    "handarty.co.kr/coex/"
    "handarty.co.kr/kintex/"
    "handarty.co.kr/eng/"
    "handarty.co.kr/chn/"
    "handarty.co.kr/halloween/"
    "handarty.co.kr/suwon/"
    "handarty.co.kr/exco/"
    "bizkpet.co.kr"
    "bizkpet.co.kr/eng"
    "hvackorea.or.kr"
    "eng.hvackorea.or.kr"
    "livinglifestyle.co.kr/"
    "livinglifestyle.co.kr/suwon/"
    "livinglifestyle.co.kr/busan/"
    "livinglifestyle.co.kr/eng/"
    "gocaf.kr"
    "gocaf.kr/suwon"
    "gocaf.kr/songdo"
    "gocaf.kr/setec"
    "gocaf.kr/kintex"
    "dtexpo.or.kr"
    "eng.dtexpo.or.kr"
    "kfarm.co.kr"
    "esan.or.kr"
    ""innogreenfarm.com"
    "torygreen.net ""
    "spacedesignfair.co.kr"
    "smartconkorea.com"
    "www.klff.co.kr"
    "megazoo.co.kr"
    "k-pet.co.kr"
    "kanacat.co.kr"
    "homelifestyleshow.com"
    "smartconsafety.com"
    "fmxkorea.com"
    "nextmobweek.com"
    "kglove.org"
    "www.smartconsafety.com"
    "comex.kr"
    "wp-test.messeesang.com/guide/"
    "komiexpo.co.kr"
    "diylifeshow.com"
    "kesgforum.com"
    "evinfra.co.kr"
    "e-sang.net"
)

# GTM 스크립트
gtm_script="https://www.googletagmanager.com/gtm.js?id=GTM-XXXXXXX"

# URL 목록에서 GTM 설치 여부 확인
for url in "${urls[@]}"
do
    if curl -s "$url" | grep -q "$gtm_script"; then
        echo "GTM is installed on $url"
    else
        echo "GTM is not installed on $url"
    fi
done